"""Course, Lesson

Revision ID: 35d70e69814e
Revises: dfb9ba7bace1
Create Date: 2024-03-24 21:23:27.699838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d70e69814e'
down_revision: Union[str, None] = 'dfb9ba7bace1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lessons', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'course_id')
    # ### end Alembic commands ###
